baseurl = "https://danielmfn.github.io/phonestico/"
title = "Phonestico"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "UA-88054481-3"

[params]
brand = "Phonestico"
description = "Tudo sobre novidades tecnol√≥gicas"
bgimg = "img/ignasi_pattern_s.png"
